// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS83G5_6WrOElV2EiTy01H1yipbWG20A0',
    appId: '1:617197621509:web:30b59f5d8cfd97349a276c',
    messagingSenderId: '617197621509',
    projectId: 'medconnect-411119',
    authDomain: 'medconnect-411119.firebaseapp.com',
    storageBucket: 'medconnect-411119.appspot.com',
    measurementId: 'G-1FNSHFJX2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-ovVRyveF_4Gn_zgWSGEWxCnii3CRDQ',
    appId: '1:617197621509:android:fb4801a66560b2569a276c',
    messagingSenderId: '617197621509',
    projectId: 'medconnect-411119',
    storageBucket: 'medconnect-411119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMgnaefTwxhmGSBozlRfKSYlKZSONt8_8',
    appId: '1:617197621509:ios:e2267c466331ac689a276c',
    messagingSenderId: '617197621509',
    projectId: 'medconnect-411119',
    storageBucket: 'medconnect-411119.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMgnaefTwxhmGSBozlRfKSYlKZSONt8_8',
    appId: '1:617197621509:ios:5a9ef5014bd30fde9a276c',
    messagingSenderId: '617197621509',
    projectId: 'medconnect-411119',
    storageBucket: 'medconnect-411119.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
